services:
  backend:
    build: ./backend
    container_name: wfcts-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    restart: always
    networks:
      - wfcts-network

  frontend:
    build: ./frontend
    container_name: wfcts-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - wfcts-network

networks:
  wfcts-network:
    driver: bridge
