const seedUsers = [
  {
    name: 'Prof. Ananya Sharma',
    email: 'teacher@wfcts.edu',
    password: 'teacher123',
    role: 'TEACHER',
    department: 'Computer Science',
  },
  {
    name: 'Prof. Neha Joshi',
    email: 'neha@wfcts.edu',
    password: 'teacher123',
    role: 'TEACHER',
    department: 'Computer Science',
  },
  {
    name: 'Prof. Arjun Mehta',
    email: 'arjun@wfcts.edu',
    password: 'teacher123',
    role: 'TEACHER',
    department: 'Computer Science',
  },
  {
    name: 'Admin User',
    email: 'admin@wfcts.edu',
    password: 'admin123',
    role: 'ADMIN',
    department: 'Administration',
  },
  {
    name: 'Dr. N. Verma',
    email: 'hod@wfcts.edu',
    password: 'hod123',
    role: 'HOD',
    department: 'Computer Science',
  },
]

const seedWorkEntries = [
  {
    teacherEmail: 'teacher@wfcts.edu',
    subject: 'Data Structures',
    className: 'FY-A',
    hours: 3,
    workType: 'Lecture',
    date: '2026-02-27',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    subject: 'Algorithms',
    className: 'SY-B',
    hours: 2,
    workType: 'Lab',
    date: '2026-02-25',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    subject: 'Operating Systems',
    className: 'TY-A',
    hours: 3,
    workType: 'Lecture',
    date: '2026-02-20',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    subject: 'Machine Learning',
    className: 'TY-B',
    hours: 4,
    workType: 'Lecture',
    date: '2026-02-18',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    subject: 'Database Management',
    className: 'SY-A',
    hours: 2,
    workType: 'Admin',
    date: '2026-02-15',
  },
  {
    teacherEmail: 'neha@wfcts.edu',
    subject: 'Computer Networks',
    className: 'SY-A',
    hours: 3,
    workType: 'Lecture',
    date: '2026-03-08',
  },
  {
    teacherEmail: 'neha@wfcts.edu',
    subject: 'Software Engineering',
    className: 'TY-A',
    hours: 2,
    workType: 'Lecture',
    date: '2026-03-06',
  },
  {
    teacherEmail: 'neha@wfcts.edu',
    subject: 'Database Management',
    className: 'SY-B',
    hours: 2,
    workType: 'Lab',
    date: '2026-03-04',
  },
  {
    teacherEmail: 'arjun@wfcts.edu',
    subject: 'Physics',
    className: 'FY-B',
    hours: 2,
    workType: 'Lecture',
    date: '2026-03-09',
  },
  {
    teacherEmail: 'arjun@wfcts.edu',
    subject: 'Mathematics II',
    className: 'FY-A',
    hours: 3,
    workType: 'Lecture',
    date: '2026-03-02',
  },
]

const seedSubstituteEntries = [
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Rao',
    date: '2026-02-28',
    status: 'Repaid',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Iyer',
    date: '2026-02-20',
    status: 'Pending',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Mehta',
    date: '2026-02-14',
    status: 'Repaid',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Rao',
    date: '2026-01-30',
    status: 'Pending',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Singh',
    date: '2026-01-22',
    status: 'Repaid',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Nair',
    date: '2026-03-03',
    status: 'Pending',
    direction: 'SUBSTITUTION',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    coveredFor: 'Prof. Kulkarni',
    date: '2026-02-26',
    status: 'Repaid',
    direction: 'SUBSTITUTION',
  },
  {
    teacherEmail: 'neha@wfcts.edu',
    coveredFor: 'Prof. Fernandes',
    date: '2026-03-07',
    status: 'Pending',
    direction: 'CREDIT',
  },
  {
    teacherEmail: 'arjun@wfcts.edu',
    coveredFor: 'Prof. Kulkarni',
    date: '2026-03-05',
    status: 'Repaid',
    direction: 'SUBSTITUTION',
  },
]

const seedTasks = [
  {
    title: 'Prepare AI Lab Plan',
    description: 'Draft weekly plan for semester AI labs.',
    assignedBy: 'Dr. N. Verma (HOD)',
    assignToEmail: 'teacher@wfcts.edu',
    deadline: '2026-03-20',
    status: 'Pending',
  },
  {
    title: 'Update Attendance Sheet',
    description: 'Consolidate attendance for Section II A.',
    assignedBy: 'Admin Office',
    assignToEmail: 'teacher@wfcts.edu',
    deadline: '2026-03-12',
    status: 'Completed',
  },
  {
    title: 'Prepare NBA Audit Notes',
    description: 'Compile recent departmental workload evidence.',
    assignedBy: 'Admin User',
    assignToEmail: 'neha@wfcts.edu',
    deadline: '2026-03-25',
    status: 'Pending',
  },
  {
    title: 'Lab Equipment Verification',
    description: 'Verify lab inventory and update discrepancy sheet.',
    assignedBy: 'Dr. N. Verma (HOD)',
    assignToEmail: 'arjun@wfcts.edu',
    deadline: '2026-03-18',
    status: 'Completed',
  },
]

const seedIndustrySessions = [
  {
    teacherEmail: 'teacher@wfcts.edu',
    title: 'Generative AI in Education',
    speaker: 'Dr. Ritu Malhotra',
    date: '2026-03-05',
    proofUploaded: true,
    proofName: 'genai-session-proof.pdf',
  },
  {
    teacherEmail: 'teacher@wfcts.edu',
    title: 'Cloud Security Essentials',
    speaker: 'Mr. Karan Joshi',
    date: '2026-02-22',
    proofUploaded: false,
    proofName: '',
  },
  {
    teacherEmail: 'neha@wfcts.edu',
    title: 'Industry 4.0 for Engineers',
    speaker: 'Ms. Pooja Menon',
    date: '2026-03-01',
    proofUploaded: true,
    proofName: 'industry4-proof.png',
  },
]

module.exports = {
  seedUsers,
  seedWorkEntries,
  seedSubstituteEntries,
  seedTasks,
  seedIndustrySessions,
}
